name: Check Osmosis mainnet

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  check_mainnet:
    runs-on: osmo-dev-runner
    steps:
      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Checkout osmosis-installer branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: 🧪 Start osmosis mainnet node
      #   run: |
      #     python3 osmosis-installer.py -i="/home/runner/.osmosisd" -ds="snapshot" -st="pruned" -sl="netherlands" -rdb="goleveldb" -es=True -sr=False -cvs="noservice"
      - name: Run the node for 50 blocks
        run: |
          CURR_BLOCK_HEIGHT=$(curl -s https://rpc.osmosis.zone/status | jq ".result.sync_info.latest_block_height| tonumber")
          HALT_BLOCK_HEIGHT=$((CURR_BLOCK_HEIGHT + 50))
          echo "Block height: $CURR_BLOCK_HEIGHT"
          echo "HALT HEIGHT: $HALT_BLOCK_HEIGHT"
          CONFIG_FOLDER=$HOME/.osmosisd/config
          # Edit app.toml
          echo "dasel put string -f $CONFIG_FOLDER/app.toml '.halt-height' "$HALT_BLOCK_HEIGHT""
          dasel put string -f $CONFIG_FOLDER/app.toml '.halt-height' "$HALT_BLOCK_HEIGHT"
          osmosisd start
      - name: 🧹 Clean up Osmosis Home
        if: always()
        run: rm -rf $HOME/.osmosisd/ || true
