name: Run installer | Mainnet

on:
  workflow_dispatch:
  push:
    branches:
      - sis/docker-test

jobs:

  run_installer_mainnet:
    runs-on: osmo-dev-runner
    #container: ubuntu:22.04
    steps:

      - 
        name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: 🧪 Run installer
        run: |
          python3 osmosis-installer.py \
            -i="$RUNNER_TEMP/.osmosisd" \
            -ds="snapshot" \
            -st="pruned" \
            -sl="netherlands" \
            -rdb="goleveldb" \
            -es=True \
            -sr=False \
            -cvs="noservice"
      - 
        name: Run the node for 50 blocks
        run: |
          CURRENT_HEIGHT=$(curl -s https://rpc.osmosis.zone/status | jq -r ".result.sync_info.latest_block_height")
          HALT_HEIGHT=$((CURRENT_HEIGHT + 50))
          
          echo "Block height: $CURRENT_HEIGHT"
          echo "Halth height: $HALT_HEIGHT"

          # Edit app.toml
          sed -i "s/halt-height = 0/halt-height = $HALT_HEIGHT/g" $RUNNER_TEMP/.osmosisd/config/app.toml
          osmosisd start --home="$RUNNER_TEMP/.osmosisd"
